name: Deployment
on:
  push:
    branches:
      - hexo-blog
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4 # 拉取博客最新源文件

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
        run: |
          npm version
          npm install
          npm run clean
          npm run algolia
          npm run build
          npm run deploy