name: Deployment
on:
  push:
    branches:
      - hexo-blog
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
        run: |
          npm install
          npm run clean
          npm run algolia
          npm run build
          npm run deploy