name: Deployment

on:
  push:
    branches:
      - hexo-blog

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
          GH_REPO: github.com/ultravires/ultravires.github.io.git
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "ultravires"
          git config --global user.email "x555666777@qq.com"
          npm version
          npm install
          npm run clean
          npm run build
          npm run algolia
          npm run deploy
