name: Deployment
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - hexo-blog
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        with:
          node-version: '20'
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
      - run: npm install
      - run: npm run clean
      - run: npm run algolia
      - run: npm run build
      - run: npm run deploy